FORMAT: 1A
HOST: http://alde.tango-project.eu/v1

# Application Lifecycle Deployment Engine

The Application Lifecycle Deployment Engine is a component of the TANGO project: http://www.tango-project.eu .

It will be responsible of informing about the hetegoregenous resources in the different testbeds. Also, it will collect the application as input, compile it to the targetted testbed and, if possible, execute it.

The Application Lifececyle Deployment Engine is being developed by Atos Research and Innovation and its code it is being relased under an Apache 2.0 license: https://www.apache.org/licenses/LICENSE-2.0

## Testbeds [/testbeds]

### List All Testbeds [GET]

+ Response 200 (application/json)

        [
            {
                id: 0,
                name: "nova_1",
                on_line: "true",
                type: "slurm",
                protocol: "ssh",
                endpoint: "user@172.0.0.1",
                package_formats: [
                    "docker",
                    "spack"
                ]
            },
            {
                id: 1,
                name: "embedded_1",
                on_line: "false",
                type: "embedded",
                protocol: "file",
                endpoint: "n/a",
                package_formats: [
                    "iso"
                ]
            }
        ]
        
### Create a new testbed [POST]

+ Request (application/json)

        {
            name: "nova_2",
            on_line: "true",
            type: "slurm",
            protocol: "ssh",
            endpoint: "user@172.0.0.2",
            package_formats: [
                "docker",
                "spack"
            ]
        }
    
+ Response 201 (application/json)

        { 
            id: 3,
            name: "nova_2",
            on_line: "true",
            type: "slurm",
            protocol: "ssh",
            endpoint: "user@172.0.0.2",
            package_formats: [
                "docker",
                "spack"
            ]
        }                                       

## Testbed [/testbeds/{testbed_id}]

+ Parameters
    + testbed_id (number) - ID of the testbed in the form of an integer
    
### View a testbed details [GET]

+ Response 200 (application/json)

        { 
            id: testbed_id,
            name: "nova_2il",
            on_line: "true",
            type: "slurm",
            protocol: "ssh",
            endpoint: "user@172.0.0.2",
            package_formats: [
                "docker",
                "spack"
            ]
        }

### Update of testbed details [PUT]

+ Request (application/json)

        {
            name: "nova_3",
        }
    
+ Response 200 (application/json)

        { 
            id: 3,
            name: "nova_3",
            on_line: "true",
            type: "slurm",
            protocol: "ssh",
            endpoint: "user@172.0.0.2",
            package_formats: [
                "docker",
                "spack"
            ]
        }   

### Delete of testbed detailes [DELETE]

This will delete the testbed from the ALDE database together with all the node information associated to that testbed
of 
+ Response 204